enum PacketId {
    Invalid = 0,
    ServerPing,
    ClientPong,
    ServerLoginReply,
    ServerUserDisconnected,
    ServerUserConnected,
    ServerAvailableChatChannel,
    ServerJoinedChatChannel,
    ServerChatMessage,
    ClientChatMessage,
    ClientRequestLeaveChatChannel,
    ServerLeftChatChannelPacket,
    ClientRequestJoinChatChannel,
    ServerFailedToJoinChannelPacket,
    ServerMuteEndTimePacket,
    ServerNotification,
    ClientStatusUpdate,
    ServerUsersOnline,
    ClientRequestUserInfo,
    ServerUserInfo,
    ClientRequestUserStatus,
    ServerUserStatus,
    ServerFailedToLogin,
    ServerChooseUsername,
    ClientLobbyJoin,
    ClientLobbyLeave,
    ClientCreateGame,
    ServerMultiplayerGameInfo,
    ServerJoinGame,
    ServerChangeGameHost,
    ClientLeaveGame,
    ServerGameDisbanded,
    ClientJoinGame,
    ServerJoinGameFailed,
    ServerUserJoinedGame,
    ServerUserLeftGame
}

export default PacketId;
